### ISSUE TITLE
how to generate ShoeV2_Cooedinate

### ISSUE THREAD

**Issue by abin333** [AyanKumarBhunia/Baseline_FGSBIR#1]
hello,i'm a student from njnu china,may i ask you a question?
i want to know that how to generate ShoeV2_Cooedinate
thank you very much

**Comment by AyanKumarBhunia** [comment]
I think you can download the original dataset from https://drive.google.com/u/0/uc?id=15s2BR-QwLgX_DObQBrYlUlZqUU90EL9G&export=download and pre-process the .SVG files.
